# Generated by Django 2.2.5 on 2022-08-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='出版社名称')),
                ('address', models.CharField(max_length=32, verbose_name='出版社地址')),
            ],
        ),
    ]
